services:
  backend:
    build: ./backend
    container_name: whatthenote-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - groq

  frontend:
    build: ./frontend
    container_name: whatthenote-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    
  groq:
    build: ./groq_service
    container_name: whatthenote-groq
    env_file:
      - ./groq_service/.env
    ports:
      - "9000:9000"