services:
  backend:
    build: ./backend
    container_name: whatthenote-backend
    env_file:
      - ./backend/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434 # overriding localhost ollama
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    container_name: whatthenote-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: whatthenote-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: