services:
  backend:
    build: ./backend
    container_name: whatthenote-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: whatthenote-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend